const R = String.raw;

const HEADER = 'src/import/headerRow.ts';
const CLASSIFY = 'src/import/details/classify.ts';
const DATE = 'src/import/date.ts';
const AMOUNT = 'src/import/amount.ts';
const NORM = 'src/import/normalizeRow.ts';
const CARD = 'src/import/details/card.ts';
const FEE = 'src/import/details/fee.ts';
const SERVICE = 'src/import/details/service.ts';
const CONV = 'src/import/details/conversion.ts';
const TRANSFER = 'src/import/details/transfer.ts';
const VALIDATE = 'src/import/validate.ts';
const BUILD = 'src/import/buildPreview.ts';
const READ = 'src/import/readWorkbook.ts';
const IDENTITY = 'src/import/identity.ts';
const TXREPO = 'src/db/transactions.ts';
const DERIVE = 'src/import/derive.ts';
const IMPORTVIEW = 'src/ui/views/ImportView.svelte';
const TXVIEW = 'src/ui/views/TransactionsView.svelte';
const PAIR = 'src/pairing/pairConversions.ts';
const RATES = 'src/pairing/rates.ts';
const CONVERT = 'src/aggregate/convert.ts';

const headerFilter = R`      .filter((cell) => cell.columnIndex > detailsIndex && cell.text !== '');`;

export const MUTATIONS = [
  ['M1  header scan starts at row 0', HEADER,
    'for (let index = 0; index < rows.length; index += 1) {',
    'for (let index = 4; index < rows.length; index += 1) {'],
  ['M2  currency header guard', HEADER,
    R`const CURRENCY_CODE = /^[A-Z]{3}$/;`, R`const CURRENCY_CODE = /^.*$/;`],
  ['M3  blank header cells ignored', HEADER, headerFilter,
    R`      .filter((cell) => cell.columnIndex > detailsIndex);`],
  ['M23 currency columns follow Details', HEADER, headerFilter,
    R`      .filter((cell) => cell.columnIndex > dateIndex && cell.text !== '');`],
  ['M25 currency keeps absolute column', HEADER,
    'columnIndex: cell.columnIndex })),', 'columnIndex: cell.columnIndex + 1 })),'],
  ['M4  classify: card branch', CLASSIFY,
    R`if (body.includes('Merchant:')) return 'card';`, R`if (body.includes('Merchant::')) return 'card';`],
  ['M29 classify: transfer branch', CLASSIFY,
    R`if (body.includes('Beneficiary:')) return 'transfer';`,
    R`if (body.includes('Beneficiary::')) return 'transfer';`],
  ['M5a classify: conversion, Foreign Exchange', CLASSIFY,
    R`body.startsWith('Foreign Exchange')`, R`body.startsWith('foreign exchange')`],
  ['M5b classify: conversion, Automatic conversion', CLASSIFY,
    R`body.startsWith('Automatic conversion')`, R`body.startsWith('automatic conversion')`],
  ['M6  classify: fee branch', CLASSIFY,
    R`if (body.startsWith('Payment Fee')) return 'fee';`, R`if (body.startsWith('Payment Fees')) return 'fee';`],
  ['M7  classify: service marker', CLASSIFY,
    R`body.includes('payment service')`, R`body.includes('payment services')`],
  ['M8  Excel serial epoch', DATE,
    'const EXCEL_EPOCH_UTC = Date.UTC(1899, 11, 30);', 'const EXCEL_EPOCH_UTC = Date.UTC(1899, 11, 31);'],
  ['M9  Date cell read as UTC', DATE,
    R`  const year = String(value.getUTCFullYear()).padStart(4, '0');
  const month = String(value.getUTCMonth() + 1).padStart(2, '0');
  const day = String(value.getUTCDate()).padStart(2, '0');`,
    R`  const year = String(value.getFullYear()).padStart(4, '0');
  const month = String(value.getMonth() + 1).padStart(2, '0');
  const day = String(value.getDate()).padStart(2, '0');`],
  ['M10 effectiveDate prefers txDateTime', DERIVE,
    'effectiveDate: fields.txDateTime?.slice(0, 10) ?? row.postingDate,',
    'effectiveDate: row.postingDate,'],
  ['M11 half-up rounding', AMOUNT,
    R`if (Number(fraction[decimals] ?? '0') >= 5) value += 1;`,
    R`if (Number(fraction[decimals] ?? '0') >= 50) value += 1;`],
  ['M12 extra-precision threshold', AMOUNT,
    'extraPrecision: fraction.length > decimals', 'extraPrecision: fraction.length > decimals + 1'],
  ['M16 numeric cell via String()', AMOUNT, 'raw = String(cell);', 'raw = cell.toFixed(2);'],
  ['M13 exactly-one-currency boundary', NORM,
    'if (present.length > 1 || only === undefined) {', 'if (present.length > 2 || only === undefined) {'],
  ['M17 counterparty truncation length', DERIVE, 'const COUNTERPARTY_MAX = 60;', 'const COUNTERPARTY_MAX = 20;'],
  ['M31 transfer counterparty is beneficiary', DERIVE,
    R`  if (kind === 'transfer') return fields.beneficiary ?? truncated;`,
    R`  if (kind === 'transfer') return truncated;`],
  ['M14 merchant before first comma', CARD,
    R`const MERCHANT = /Merchant:\s*([^,]*)/;`, R`const MERCHANT = /Merchant:\s*(.*)/;`],
  ['M19 card last4 pattern', CARD,
    R`const CARD_LAST4 = /Card(?:\s*(?:No\.?|Number|number))?\s*[:.]?\s*\*{0,6}(\d{4})\b/i;`,
    R`const CARD_LAST4 = /(\d{4})/;`],
  ['M20 conversion rate keeps decimals', CONV,
    R`const RATE = /rate:?\s*(\d+(?:\.\d+)?)/i;`, R`const RATE = /rate:?\s*(\d+)/i;`],
  ['M21 service payee segment', SERVICE,
    R`payee: segmentAfter(body, 'payment service,'),`, R`payee: segmentAfter(body, 'Payment,'),`],
  ['M28a payment code separator (service)', SERVICE,
    R`const PAYMENT_CODE = /payment code\s*[-:]?\s*([^\s,;]+)/i;`,
    R`const PAYMENT_CODE = /payment code\s*:?\s*([^\s,;]+)/i;`],
  ['M22 fee payee segment', FEE,
    R`payee: segmentAfter(body, 'payment service,') ?? segmentAfter(body, 'Payment Fee,'),`,
    R`payee: segmentAfter(body, 'Payment Fee,'),`],
  ['M28b payment code separator (fee)', FEE,
    R`const PAYMENT_CODE = /payment code\s*[-:]?\s*([^\s,;]+)/i;`,
    R`const PAYMENT_CODE = /payment code\s*:?\s*([^\s,;]+)/i;`],
  ['M30 beneficiary stops at semicolon', TRANSFER,
    R`const BENEFICIARY = /Beneficiary:\s*([^;]*)/;`, R`const BENEFICIARY = /Beneficiary:\s*(.*)/;`],
  ['M32 precision warning is emitted', VALIDATE,
    'if (extraPrecisionCell === null) return [];', 'if (extraPrecisionCell !== undefined) return [];'],
  ['M18 sheet selected by name', READ,
    'const match = sheets.find((sheet) => sheet.sheet === sheetName);', 'const match = sheets[0];'],
  ['M24 blank-row skip', BUILD,
    'if (row.every(isBlank)) continue;', 'if (row.every(isBlank) && row.length > 1000) continue;'],

  ['M33 occurrence index increments', IDENTITY,
    'seen.set(tuple, occurrence + 1);', 'seen.set(tuple, occurrence);'],
  ['M34 id carries the occurrence', IDENTITY,
    'return { ...row, id: rowId(row, occurrence) };', 'return { ...row, id: rowId(row, 0) };'],
  ['M35 id includes the amount', IDENTITY,
    'return JSON.stringify([row.postingDate, row.currency, row.amountMinor, row.details, occurrence]);',
    'return JSON.stringify([row.postingDate, row.currency, row.details, occurrence]);'],
  ['M36 known ids are the duplicates', IDENTITY,
    'if (existing.has(row.id)) duplicates.push(row);', 'if (!existing.has(row.id)) duplicates.push(row);'],
  ['M37 existing ids are reported', TXREPO,
    'return new Set(found);', 'return new Set(found.slice(0, 0));'],
  ['M38 putMany persists', TXREPO,
    'if (rows.length === 0) return;', 'if (rows.length >= 0) return;'],
  ['M39 listAll reads the table', TXREPO,
    'const stored = await db.transactions.toArray();', 'const stored: StoredTransaction[] = [];'],
  ['M68 rows derive from their own details', TXREPO,
    'return stored.map((row) => ({ ...row, ...deriveFields(row) }));',
    "return stored.map((row) => ({ ...row, ...deriveFields({ ...row, details: '' }) }));"],
  ['M40 confirm persists new rows', IMPORTVIEW,
    'if (newRows.length === 0) return;', 'if (newRows.length > 0) return;'],
  ['M41 confirmed rows become duplicates', IMPORTVIEW,
    'duplicates = [...duplicates, ...newRows];', 'duplicates = [...duplicates];'],
  ['M42 sort direction follows ascending', TXVIEW,
    'const direction = ascending ? 1 : -1;', 'const direction = ascending ? -1 : 1;'],
  ['M43 default order is newest first', TXVIEW,
    'let ascending = $state(false);', 'let ascending = $state(true);'],
  ['M44 second click reverses', TXVIEW,
    'if (sortKey === key) ascending = !ascending;', 'if (sortKey === key) ascending = true;'],
  ['M45 chosen column becomes the sort key', TXVIEW,
    'sortKey = key;', "sortKey = 'effectiveDate';"],
  ['M46 aria-sort marks the chosen column', TXVIEW,
    "if (sortKey !== key) return 'none';", "if (sortKey === key) return 'none';"],
  ['M47 empty state threshold', TXVIEW,
    '{#if sorted.length === 0}', '{#if sorted.length <= 1}'],
  ['M48 amount carries its currency', TXVIEW,
    'return `${formatMinor(row.amountMinor)} ${row.currency}`;',
    'return `${formatMinor(row.amountMinor)}`;'],
  ['M49 counterparty column shows counterparty', TXVIEW,
    '<td>{row.counterparty}</td>', '<td>{row.details}</td>'],

  ['M50 rate scale matches its decimals', CONV,
    'const RATE_DECIMALS = 6;', 'const RATE_DECIMALS = 4;'],
  ['M51 rate trims every trailing zero', CONV,
    "replace(/0+$/, '')", "replace(/0$/, '')"],
  ['M52 rateless rows never pair', PAIR,
    'if (row.conversionRateScaled === null) {', 'if (row.conversionRateScaled !== null) {'],
  ['M53 pair key includes the rate', PAIR,
    'return `${row.postingDate}|${row.conversionRateScaled}`;', 'return `${row.postingDate}`;'],
  ['M54 pair requires opposite signs', PAIR,
    '=== -Math.sign(gel.amountMinor)', '=== Math.sign(gel.amountMinor)'],
  ['M55 leftover foreign rows are unpaired', PAIR,
    'for (const row of available) unpaired.push(row.id);',
    'for (const row of available.slice(0, 0)) unpaired.push(row.id);'],
  ['M56 base side of a pair is GEL', PAIR,
    "const BASE_CURRENCY = 'GEL';", "const BASE_CURRENCY = 'USD';"],
  ['M57 rate applies on or before the date', RATES,
    'if (rate.date > onOrBefore) break;', 'if (rate.date >= onOrBefore) break;'],
  ['M58 rate lookup filters by currency', RATES,
    'if (rate.currency !== currency) continue;', 'if (rate.currency === currency) continue;'],
  ['M59 rate table is oldest first', RATES,
    ': a.date < b.date ? -1 : 1,', ': a.date < b.date ? 1 : -1,'],
  ['M60 conversion rounds half-up', CONVERT,
    '? whole + 1 : whole;', '? whole : whole;'],
  ['M61 conversion keeps the sign', CONVERT,
    'return negative ? -rounded : rounded;', 'return negative ? rounded : rounded;'],
  ['M62 GEL rows need no rate', TXVIEW,
    'if (row.currency === BASE_CURRENCY) return formatMinor(row.amountMinor);',
    'if (row.currency !== BASE_CURRENCY) return formatMinor(row.amountMinor);'],
  ['M63 missing rate is marked', TXVIEW,
    "const MISSING_RATE = 'no rate';", "const MISSING_RATE = '';"],
  ['M64 pair status is for conversions only', TXVIEW,
    "if (row.kind !== 'conversion') return '';", "if (row.kind === 'conversion') return '';"],
  ['M65 a pair id means paired', TXVIEW,
    "return row.paired ? 'paired' : 'unpaired';",
    "return row.paired ? 'unpaired' : 'paired';"],
  ['M66 rate table uses paired rows', TXVIEW,
    'row.paired && row.currency !== BASE_CURRENCY',
    '!row.paired && row.currency !== BASE_CURRENCY'],
  ['M67 any unpaired conversion warns', IMPORTVIEW,
    '{#if unpairedCount > 0}', '{#if unpairedCount > 1}'],
];
